#!/bin/bash

# SELinux wrapper
#
# We need this script to ensure SELinux transitions the executed JVM into correct domain

export LANG=en_US.utf8
exec /usr/bin/java "$@" -jar /usr/share/java/cfal-restapi/cfal-restapi.jar \
--spring.config.additional-location=/etc/gdc/cfal-restapi.properties